[package]
name = "overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

eframe = { version = "0.27", features = ["default_fonts"] }
egui = "0.27"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
screenshots = "0.8"
cpal = "0.15"
opus = "0.3"

[build-dependencies]
bindgen = "0.72"
vcpkg = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
ksni = "0.2"
x11rb = { version = "0.13", features = ["allow-unsafe-code"] }
raw-window-handle = "0.6"

[target.'cfg(windows)'.dependencies]
# Needed for transparent click-through windows on Windows
winapi = { version = "0.3", features = ["winuser", "wingdi"] }
tray-icon = "0.14"
